### ISSUE TITLE
content-warp.blockquote 很难看

### ISSUE THREAD

**Issue by ousui** [wszgxa/hexo-theme-simple#2]
只设置了 ul 没设置 ol，另外建议两篇 文章之间加一条分割线。

![image](https://cloud.githubusercontent.com/assets/2839512/17848056/0f85dd7c-6884-11e6-9aad-349afcd95901.png)
![image](https://cloud.githubusercontent.com/assets/2839512/17848060/14729730-6884-11e6-9ecb-9edbb62fb3e6.png)
![image](https://cloud.githubusercontent.com/assets/2839512/17848084/3b0e0be0-6884-11e6-828c-44bafe842d65.png)

**Comment by wszgxa** [comment]
你是在> 后面写了一堆列表？后面可能会加吧。。。
